name: Build simple demo

on:
  push:
    branches: 
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
        
    - name: Set up JDK 8 for Maven build
      uses: actions/setup-java@v1
      with:
        java-version: 8

    # 完成java项目打包
    - name: Build Maven project
      run: mvn clean -U package -Dmaven.test.skip 

    - name: Build Spring Cloud demo for linux/amd64
      uses: huaweicloud/swr-multiplatform-build-action@v1.2.0
      with:
        image_tag: swr.cn-north-4.myhuaweicloud.com/hcloudcli/jdkdemo:jdk19-v1.0.0.4